//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_AgentOrder
    {
        public System.Guid Id { get; set; }
        public System.Guid Agent_Id { get; set; }
        public System.Guid Order_Id { get; set; }
        public string Order_Ref { get; set; }
        public string Microsite_Id { get; set; }
        public System.Guid Currency_Id { get; set; }
        public Nullable<System.Guid> AdultTicket_Id { get; set; }
        public int AdultTicketQuantity { get; set; }
        public decimal AdultTicketCost { get; set; }
        public Nullable<System.Guid> ChildTicket_Id { get; set; }
        public int ChildTicketQuantity { get; set; }
        public decimal ChildTicketCost { get; set; }
        public Nullable<System.Guid> FamilyTicket_Id { get; set; }
        public int FamilyTicketQuantity { get; set; }
        public decimal FamilyTicketCost { get; set; }
        public decimal OrderTotal { get; set; }
        public decimal CommissionTotal { get; set; }
        public bool CommissionRaised { get; set; }
        public bool CommissionPaid { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> CommissionRaisedById { get; set; }
        public Nullable<System.DateTime> CommissionRaisedDate { get; set; }
        public Nullable<System.Guid> CommissionPaidById { get; set; }
        public Nullable<System.DateTime> CommissionPaidDate { get; set; }
        public string OrderTypeTorA { get; set; }
        public string CommissionPaidByName { get; set; }
        public string CommissionRaisedByName { get; set; }
        public string RefundReason { get; set; }
        public bool IsCashSale { get; set; }
        public bool IsRemittanceSale { get; set; }
        public bool IsTradeTicketSale { get; set; }
        public Nullable<System.Guid> InfantTicket_Id { get; set; }
        public int InfantTicketQuantity { get; set; }
        public decimal InfantTicketCost { get; set; }
    }
}
