//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_AccountManager_MicroSite
    {
        public System.Guid Id { get; set; }
        public System.Guid AccountManager_Id { get; set; }
        public string Microsite_Id { get; set; }
    
        public virtual tb_AccountManager tb_AccountManager { get; set; }
        public virtual tb_MicroSite tb_MicroSite { get; set; }
    }
}
