//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_AdminUser
    {
        public string Id { get; set; }
        public string Password { get; set; }
        public string PasswordHash { get; set; }
        public int PasswordVersion { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Enabled { get; set; }
        public string CreatedBy_Id { get; set; }
        public string EnabledBy_Id { get; set; }
        public string Email { get; set; }
        public string Type { get; set; }
    }
}
