//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_AgentOrderError
    {
        public System.Guid Id { get; set; }
        public string IpAddress { get; set; }
        public string DeviceAgent { get; set; }
        public string DeviceBrowser { get; set; }
        public System.DateTime DateSubmitted { get; set; }
        public string AgentRef { get; set; }
        public string AgentEmail { get; set; }
        public string CustomerName { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string ApproximateTime { get; set; }
        public string Description { get; set; }
    }
}
