//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_AgentCashSale
    {
        public System.Guid Id { get; set; }
        public System.Guid Agent_Id { get; set; }
        public int Pin { get; set; }
        public decimal CreditLimit { get; set; }
        public decimal BalanceAlertLimit { get; set; }
        public decimal CurrentBalance { get; set; }
        public decimal CurrentTotal { get; set; }
    }
}
