//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_AgentProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_AgentProfile()
        {
            this.tb_User = new HashSet<tb_User>();
        }
    
        public string Id { get; set; }
        public System.Guid CreatedBy_Id { get; set; }
        public string CreatedBy_Name { get; set; }
        public System.Guid ModifiedBy_Id { get; set; }
        public string ModifiedBy_Name { get; set; }
        public Nullable<System.Guid> AccountManager_Id { get; set; }
        public string AccountManager_Name { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateLastModified { get; set; }
        public bool RequiresPasswordToViewAccountHistory { get; set; }
        public string AccountHistoryPassword { get; set; }
        public string AccountHistoryPasswordHash { get; set; }
        public int AccountHistoryPasswordVersion { get; set; }
    
        public virtual tb_AccountManager tb_AccountManager { get; set; }
        public virtual tb_AccountManager tb_AccountManager1 { get; set; }
        public virtual tb_AccountManager tb_AccountManager2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_User> tb_User { get; set; }
    }
}
