//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_AdminSession
    {
        public System.Guid Id { get; set; }
        public string AdminUser_Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string AdminMode { get; set; }
    }
}
