//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_AccountManager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_AccountManager()
        {
            this.tb_AccountManager_MicroSite = new HashSet<tb_AccountManager_MicroSite>();
            this.tb_AgentProfile = new HashSet<tb_AgentProfile>();
            this.tb_AgentProfile1 = new HashSet<tb_AgentProfile>();
            this.tb_AgentProfile2 = new HashSet<tb_AgentProfile>();
        }
    
        public System.Guid Id { get; set; }
        public string Password { get; set; }
        public string PasswordHash { get; set; }
        public int PasswordVersion { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string CreatedBy_Id { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ContactTel { get; set; }
        public bool SuperManager { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_AccountManager_MicroSite> tb_AccountManager_MicroSite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_AgentProfile> tb_AgentProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_AgentProfile> tb_AgentProfile1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_AgentProfile> tb_AgentProfile2 { get; set; }
    }
}
