//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Basket_Promotion
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Basket_Id { get; set; }
        public string Promotion_Id { get; set; }
        public bool PromotionApplied { get; set; }
    
        public virtual tb_Basket tb_Basket { get; set; }
        public virtual tb_Promotion tb_Promotion { get; set; }
    }
}
