//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Barcode
    {
        public System.Guid Id { get; set; }
        public string Microsite_Id { get; set; }
        public string Ticket_Type { get; set; }
        public string BarcodePrefix { get; set; }
        public Nullable<int> NextAvailableBarcode { get; set; }
        public int NextAvailableDrBarcode { get; set; }
        public string Ticket_TicketType { get; set; }
        public Nullable<System.Guid> Ticket_Id { get; set; }
    
        public virtual tb_MicroSite tb_MicroSite { get; set; }
    }
}
