//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Basket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Basket()
        {
            this.tb_Basket_Promotion = new HashSet<tb_Basket_Promotion>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> User_Id { get; set; }
        public Nullable<System.Guid> Currency_Id { get; set; }
        public decimal Total { get; set; }
        public string LeadTravelerName { get; set; }
        public string GiftTravelerName { get; set; }
        public string ExternalBarcode { get; set; }
        public string ExternalOrderId { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Basket_Promotion> tb_Basket_Promotion { get; set; }
    }
}
