//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CustomPage_Language
    {
        public System.Guid Id { get; set; }
        public System.Guid CustomPage_Id { get; set; }
        public string Language_Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public bool IsLive { get; set; }
        public string SideBarText { get; set; }
        public string Introduction { get; set; }
    }
}
