//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DownloadFolder
    {
        public System.Guid Id { get; set; }
        public string FolderName { get; set; }
        public Nullable<System.Guid> ParentFolder_Id { get; set; }
    }
}
