//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Email
    {
        public System.Guid Id { get; set; }
        public string FromAddress { get; set; }
        public string ReplyToAddress { get; set; }
        public string ToAddresses { get; set; }
        public string CCAddresses { get; set; }
        public string BCCAddresses { get; set; }
        public string Subject { get; set; }
        public string HTMLBody { get; set; }
        public string TextBody { get; set; }
        public int PriorityLevel { get; set; }
        public bool ReadyToSend { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateFirstAttempted { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
    }
}
