//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_GoogleCode
    {
        public System.Guid Id { get; set; }
        public string Code_Function { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string Optimisation_Default_Head { get; set; }
        public string Optimisation_Default_Footer { get; set; }
        public bool IsActive { get; set; }
        public string Test_Page_Header { get; set; }
        public string Test_Page_Footer { get; set; }
    }
}
