//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_GroupBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_GroupBooking()
        {
            this.tb_GroupBooking_Stop = new HashSet<tb_GroupBooking_Stop>();
            this.tb_GroupBooking_Time = new HashSet<tb_GroupBooking_Time>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string MicroSite_Id { get; set; }
        public bool AvailableMonday { get; set; }
        public bool AvailableTuesday { get; set; }
        public bool AvailableWednesday { get; set; }
        public bool AvailableThursday { get; set; }
        public bool AvailableFriday { get; set; }
        public bool AvailableSaturday { get; set; }
        public bool AvailableSunday { get; set; }
        public bool Available0900 { get; set; }
        public bool Available1000 { get; set; }
        public bool Available1100 { get; set; }
        public bool Available1200 { get; set; }
        public bool Available1300 { get; set; }
        public bool Available1400 { get; set; }
        public bool Available1500 { get; set; }
        public bool Available1600 { get; set; }
        public bool Available1700 { get; set; }
        public bool Available1800 { get; set; }
        public bool IsLive { get; set; }
        public string Ticket_Name { get; set; }
        public string Ticket_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_GroupBooking_Stop> tb_GroupBooking_Stop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_GroupBooking_Time> tb_GroupBooking_Time { get; set; }
    }
}
