//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HomePageData
    {
        public System.Guid Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime UtcDateCreated { get; set; }
        public string MicroSite_Id { get; set; }
        public string Language_Id { get; set; }
        public Nullable<System.Guid> TopImage_Id { get; set; }
        public Nullable<System.Guid> ExploreImageLeft_Id { get; set; }
        public Nullable<System.Guid> ExploreImageMiddle_Id { get; set; }
        public Nullable<System.Guid> ExploreImageRight_Id { get; set; }
    }
}
