//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Image
    {
        public System.Guid Id { get; set; }
        public byte[] Data { get; set; }
        public string Type { get; set; }
        public Nullable<System.Guid> xImageMetadata_Id { get; set; }
        public Nullable<System.Guid> xImageFolder_Id { get; set; }
        public string xTags { get; set; }
    
        public virtual tb_ImageFolder tb_ImageFolder { get; set; }
        public virtual tb_ImageMetaData tb_ImageMetaData { get; set; }
    }
}
