//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_MultiTicket_Promotion
    {
        public System.Guid Id { get; set; }
        public int Ident { get; set; }
        public string Promotion_Id { get; set; }
        public string Ticket_Id { get; set; }
        public string Ticket_Name { get; set; }
        public string iDex { get; set; }
        public string Checked { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
