//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_MicroSite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_MicroSite()
        {
            this.tb_AccountManager_MicroSite = new HashSet<tb_AccountManager_MicroSite>();
            this.tb_Barcode = new HashSet<tb_Barcode>();
            this.tb_MicroSite_Language = new HashSet<tb_MicroSite_Language>();
            this.tb_Navigation = new HashSet<tb_Navigation>();
            this.tb_Route = new HashSet<tb_Route>();
        }
    
        public string Id { get; set; }
        public string Language_Id { get; set; }
        public string Currency_Id { get; set; }
        public Nullable<System.Guid> RedTour_Id { get; set; }
        public Nullable<System.Guid> BlueTour_Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> HomeOfferImage_Id { get; set; }
        public string Mode { get; set; }
        public bool MultilingualActive { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public int Offer_Id { get; set; }
        public string DotNetTimeZone { get; set; }
        public string DotNetTimeZoneStandardName { get; set; }
        public string ContactDetails { get; set; }
        public string ContactNumber { get; set; }
        public bool CollectTickets { get; set; }
        public string CollectTicketsDetails { get; set; }
        public bool IsUS { get; set; }
        public bool UseQR { get; set; }
        public string RefundEmail { get; set; }
        public bool ShowTrustPilotCode { get; set; }
        public string TrustPilotUrl { get; set; }
        public string AffiliateWindowMerchantId { get; set; }
        public string AffiliateWindowTourCommissionLabel { get; set; }
        public string AffiliateWindowAttractionCommissionLabel { get; set; }
        public Nullable<int> ViatorWidgetDestinationId { get; set; }
        public string GoogleRemarketingConversionId { get; set; }
        public string GoogleRemarketingConversionLabel { get; set; }
        public bool ECRVersion2Enabled { get; set; }
        public bool IsActiveAgentTandC { get; set; }
        public int EcrVersionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_AccountManager_MicroSite> tb_AccountManager_MicroSite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Barcode> tb_Barcode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_MicroSite_Language> tb_MicroSite_Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Navigation> tb_Navigation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Route> tb_Route { get; set; }
    }
}
