//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NewsletterStaticSection
    {
        public System.Guid Id { get; set; }
        public string Header { get; set; }
        public string Footer { get; set; }
        public string Title { get; set; }
        public string Section_Begin { get; set; }
        public string MainHeading_Begin { get; set; }
        public string MainHeading_End { get; set; }
        public string InThisIssue_Begin { get; set; }
        public string InThisIssue_Separator { get; set; }
        public string InThisIssue_End { get; set; }
        public string Section_End { get; set; }
        public string SampleTitle { get; set; }
        public string SampleContent { get; set; }
        public string SampleInThisIssue { get; set; }
        public string SampleInThisIssueList { get; set; }
    }
}
