//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NavigationItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_NavigationItem()
        {
            this.tb_NavigationItem_Language = new HashSet<tb_NavigationItem_Language>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Navigation_Id { get; set; }
        public Nullable<int> Position { get; set; }
        public string ServerURL { get; set; }
        public Nullable<System.Guid> Parent_Id { get; set; }
        public string URL { get; set; }
    
        public virtual tb_Navigation tb_Navigation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_NavigationItem_Language> tb_NavigationItem_Language { get; set; }
    }
}
