//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NewsletterText_Language
    {
        public System.Guid Id { get; set; }
        public int Ident { get; set; }
        public string Newsletter_Id { get; set; }
        public string NewsletterText_Id { get; set; }
        public string LiveText { get; set; }
        public string DraftText { get; set; }
        public string Language_Id { get; set; }
    
        public virtual tb_NewsletterText_Language tb_NewsletterText_Language1 { get; set; }
        public virtual tb_NewsletterText_Language tb_NewsletterText_Language2 { get; set; }
    }
}
