//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NewsletterComposite
    {
        public System.Guid Id { get; set; }
        public int Ident { get; set; }
        public Nullable<System.Guid> Newsletter_Id { get; set; }
        public string Header { get; set; }
        public string Footer { get; set; }
        public string Body { get; set; }
        public string Composite { get; set; }
    }
}
