//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NewsItem
    {
        public string Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string MicroSite_Id { get; set; }
        public string Name { get; set; }
        public string Headline { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public bool IsLive { get; set; }
        public bool IsMainDisplayItem { get; set; }
    }
}
