//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Newsletter
    {
        public System.Guid Id { get; set; }
        public int Ident { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> DateSentToCustomer { get; set; }
        public Nullable<System.DateTime> DateSentToAgent { get; set; }
        public Nullable<bool> ReadyToSend { get; set; }
    }
}
