//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_OrderLine_GeneratedBarcode
    {
        public System.Guid Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> OrderLine_Id { get; set; }
        public string GeneratedBarcode { get; set; }
        public Nullable<System.DateTime> RedeemedDate { get; set; }
        public Nullable<System.DateTime> RefundDate { get; set; }
        public string RefundReason { get; set; }
        public string Comments { get; set; }
    }
}
