//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Order()
        {
            this.tb_Orderline = new HashSet<tb_Orderline>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> User_Id { get; set; }
        public string eMailAddress { get; set; }
        public Nullable<System.Guid> Currency_Id { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> OpenForPrinting { get; set; }
        public string PaymentMethod { get; set; }
        public string UserName { get; set; }
        public string LeadTravelerName { get; set; }
        public Nullable<System.Guid> Company_Id { get; set; }
        public Nullable<decimal> AgentDiscount { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public string CCLast4Digits { get; set; }
        public int OrderNumber { get; set; }
        public string Language_Id { get; set; }
        public string GiftTravelerName { get; set; }
        public bool NotificationEmailSent { get; set; }
        public bool ShowGoogleCode { get; set; }
        public Nullable<int> NumbViewPDF { get; set; }
        public Nullable<System.DateTime> DatePDFLastViewed { get; set; }
        public string Centinel_OrderId { get; set; }
        public string Centinel_TransactionId { get; set; }
        public string Centinel_Enrolled { get; set; }
        public string Centinel_ErrorNo { get; set; }
        public string Centinel_ErrorDesc { get; set; }
        public string Centinel_ECI { get; set; }
        public string Centinel_ACSURL { get; set; }
        public string Centinel_PAYLOAD { get; set; }
        public string Centinel_PIType { get; set; }
        public string Centinel_TransactionType { get; set; }
        public string Centinel_PAResStatus { get; set; }
        public string Centinel_SignatureVerification { get; set; }
        public string Centinel_TermURL { get; set; }
        public string Centinel_XID { get; set; }
        public string Centinel_CAVV { get; set; }
        public string Centinel_DIG { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string AgentRef { get; set; }
        public string ClientIp { get; set; }
        public Nullable<System.Guid> PaymentTransaction_Id { get; set; }
        public string AuthCodeNumber { get; set; }
        public bool OrderConfirmationViewed { get; set; }
        public bool SentQrCodeToMobile { get; set; }
        public string QrCodeUniqueHash { get; set; }
        public bool IsMobileAppOrder { get; set; }
        public Nullable<System.Guid> Basket_Id { get; set; }
        public Nullable<System.Guid> Session_Id { get; set; }
        public string WorldPayMerchantId { get; set; }
        public string GatewayReference { get; set; }
        public string NameOnCard { get; set; }
        public string PayPal_Token { get; set; }
        public string PayPal_Order_Id { get; set; }
        public string PayPal_Payer_Id { get; set; }
        public string EcrBookingBarCode { get; set; }
        public string EcrBookingShortReference { get; set; }
        public string EcrSupplierConfirmationNumber { get; set; }
        public string ExternalBarcode { get; set; }
        public string ExternalOrderId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Orderline> tb_Orderline { get; set; }
    }
}
