//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Orderline
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Order_Id { get; set; }
        public Nullable<System.Guid> Ticket_Id { get; set; }
        public Nullable<bool> FixedDateTicket { get; set; }
        public Nullable<System.DateTime> TicketDate { get; set; }
        public string TicketType { get; set; }
        public Nullable<int> TicketQuantity { get; set; }
        public Nullable<decimal> TicketCost { get; set; }
        public string Promotion_Id { get; set; }
        public string Promotion_Value { get; set; }
        public Nullable<decimal> GrossOrderLineValue { get; set; }
        public Nullable<decimal> NettOrderLineValue { get; set; }
        public string DepartureTimeHour { get; set; }
        public string DepartureTimeMinute { get; set; }
        public string DeparturePoint { get; set; }
        public string Microsite_Id { get; set; }
        public string TicketTOrA { get; set; }
        public string AttractionName { get; set; }
        public string GeneratedBarcode { get; set; }
        public Nullable<bool> IsPromotionTicket { get; set; }
        public string PromotionType { get; set; }
        public Nullable<System.DateTime> TicketRedeemedDate { get; set; }
        public Nullable<System.DateTime> TicketAttractionDate { get; set; }
        public string TicketAttractionTimeHour { get; set; }
        public string TicketAttractionTimeMin { get; set; }
        public string AttractionTimeSection { get; set; }
    
        public virtual tb_Order tb_Order { get; set; }
    }
}
