//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PaymentTransaction
    {
        public System.Guid Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string GatewayReference { get; set; }
        public string GatewayName { get; set; }
        public string GatewaySessionId { get; set; }
        public string AquirerResponse { get; set; }
        public string CVCResponse { get; set; }
        public string AVSResponse { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorMessage { get; set; }
        public bool FailedValidation { get; set; }
        public byte[] EncryptedDetail { get; set; }
        public string GatewayCookie { get; set; }
        public string IssuerUrl { get; set; }
        public string GatewayEchoData { get; set; }
        public string IssuerPaRequest { get; set; }
        public string TransactionType { get; set; }
        public string CardType { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
