//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PlaceOfInterest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_PlaceOfInterest()
        {
            this.tb_PlaceOfInterest_Language = new HashSet<tb_PlaceOfInterest_Language>();
            this.tb_PlaceOfInterest_Stop = new HashSet<tb_PlaceOfInterest_Stop>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> Ticket_Id { get; set; }
        public string MicroSite_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PlaceOfInterest_Language> tb_PlaceOfInterest_Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PlaceOfInterest_Stop> tb_PlaceOfInterest_Stop { get; set; }
        public virtual tb_Ticket tb_Ticket { get; set; }
    }
}
