//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PlaceOfInterest_Stop
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PlaceOfInterest_Id { get; set; }
        public Nullable<System.Guid> Stop_Id { get; set; }
    
        public virtual tb_PlaceOfInterest tb_PlaceOfInterest { get; set; }
        public virtual tb_Stop tb_Stop { get; set; }
    }
}
