//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Stop_Language
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Stop_Id { get; set; }
        public string Language_Id { get; set; }
        public string GeneralText { get; set; }
        public string AdditionalText { get; set; }
        public bool IsLiveVersion { get; set; }
    
        public virtual tb_Language tb_Language { get; set; }
        public virtual tb_Stop tb_Stop { get; set; }
    }
}
