//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Stop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Stop()
        {
            this.tb_GroupBooking_Stop = new HashSet<tb_GroupBooking_Stop>();
            this.tb_PlaceOfInterest_Stop = new HashSet<tb_PlaceOfInterest_Stop>();
            this.tb_Route_Stop = new HashSet<tb_Route_Stop>();
            this.tb_Stop_Language = new HashSet<tb_Stop_Language>();
        }
    
        public System.Guid Id { get; set; }
        public string ExistingSiteText { get; set; }
        public Nullable<int> TempId { get; set; }
        public string StopName { get; set; }
        public string MicroSite_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_GroupBooking_Stop> tb_GroupBooking_Stop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PlaceOfInterest_Stop> tb_PlaceOfInterest_Stop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Route_Stop> tb_Route_Stop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Stop_Language> tb_Stop_Language { get; set; }
    }
}
