//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Session
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PaymentTransaction_Id { get; set; }
        public Nullable<System.Guid> Basket_Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> User_Id { get; set; }
        public Nullable<System.Guid> AgentManagerId { get; set; }
        public Nullable<System.DateTime> DateToExpire { get; set; }
        public string Currency_Id { get; set; }
        public string PayPal_Order_Id { get; set; }
        public string PayPal_Token { get; set; }
        public string PayPal_Payer_Id { get; set; }
        public string Centinel_OrderId { get; set; }
        public string Centinel_TransactionId { get; set; }
        public string Centinel_Enrolled { get; set; }
        public string Centinel_ErrorNo { get; set; }
        public string Centinel_ErrorDesc { get; set; }
        public string Centinel_ECI { get; set; }
        public string Centinel_ACSURL { get; set; }
        public string Centinel_PAYLOAD { get; set; }
        public string Centinel_PIType { get; set; }
        public string Centinel_TransactionType { get; set; }
        public System.DateTime DateModified { get; set; }
        public string Message { get; set; }
        public string Centinel_PAResStatus { get; set; }
        public string Centinel_SignatureVerification { get; set; }
        public string Centinel_TermURL { get; set; }
        public string Centinel_XID { get; set; }
        public string Centinel_CAVV { get; set; }
        public string Centinel_DIG { get; set; }
        public bool IsMobileAppSession { get; set; }
        public bool InCheckoutProccess { get; set; }
        public bool InOrderCreationProcess { get; set; }
        public bool AgentUseCustomersAddress { get; set; }
        public Nullable<System.Guid> AgentFakeUser_Id { get; set; }
        public bool AgentIsTradeTicketSale { get; set; }
        public string AgentNameToPrintOnTicket { get; set; }
        public bool InPaypalCheckoutProcess { get; set; }
        public bool BookingTimesNeedsConfirming { get; set; }
    }
}
