//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TicketCost
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Ticket_Id { get; set; }
        public Nullable<System.Guid> Currency_Id { get; set; }
        public Nullable<decimal> AdultTicketCost { get; set; }
        public Nullable<decimal> ChildTicketCost { get; set; }
        public Nullable<decimal> FamilyTicketCost { get; set; }
        public Nullable<decimal> ConcessionTicketCost { get; set; }
        public Nullable<decimal> GroupAdultTicketCost { get; set; }
        public Nullable<decimal> GroupChildTicketCost { get; set; }
        public Nullable<decimal> AgentAdultTicketCost { get; set; }
        public Nullable<decimal> AgentChildTicketCost { get; set; }
        public Nullable<decimal> AgentFamilyTicketCost { get; set; }
        public Nullable<decimal> AgentConcessionTicketCost { get; set; }
        public Nullable<decimal> AgentGroupAdultTicketCost { get; set; }
        public Nullable<decimal> AgentGroupChildTicketCost { get; set; }
        public Nullable<decimal> InfantTicketCost { get; set; }
        public Nullable<decimal> AgentInfantTicketCost { get; set; }
    
        public virtual tb_Ticket tb_Ticket { get; set; }
    }
}
