//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TourAnimationContent
    {
        public System.Guid Id { get; set; }
        public string Content_Id { get; set; }
        public string Header { get; set; }
        public string Content { get; set; }
        public string Image_Id { get; set; }
        public int Position { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int AnimationType { get; set; }
        public Nullable<System.Guid> ImageMetaData_Id { get; set; }
    }
}
