//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Ticket_ExclusionWeekday
    {
        public System.Guid Id { get; set; }
        public System.Guid Ticket_Id { get; set; }
        public bool ExcludeSundays { get; set; }
        public bool ExcludeMondays { get; set; }
        public bool ExcludeTuesdays { get; set; }
        public bool ExcludeWednesdays { get; set; }
        public bool ExcludeThursdays { get; set; }
        public bool ExcludeFridays { get; set; }
        public bool ExcludeSaturdays { get; set; }
        public string AdminUser_Id { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual tb_Ticket tb_Ticket { get; set; }
    }
}
