//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TicketCostVariation
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Ticket_Id { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> DaySpecific { get; set; }
        public Nullable<bool> ValidMonday { get; set; }
        public Nullable<bool> ValidTuesday { get; set; }
        public Nullable<bool> ValidWednesday { get; set; }
        public Nullable<bool> ValidThursday { get; set; }
        public Nullable<bool> ValidFriday { get; set; }
        public Nullable<bool> ValidSaturday { get; set; }
        public Nullable<bool> ValidSunday { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string VariationType { get; set; }
        public Nullable<decimal> PercentageValue { get; set; }
        public Nullable<decimal> DollarAdultTicketCost { get; set; }
        public Nullable<decimal> DollarChildTicketCost { get; set; }
        public Nullable<decimal> DollarFamilyTicketCost { get; set; }
        public Nullable<decimal> DollarConcessionTicketCost { get; set; }
        public Nullable<decimal> DollarGroupAdultTicketCost { get; set; }
        public Nullable<decimal> DollarGroupChildTicketCost { get; set; }
        public Nullable<decimal> EuroAdultTicketCost { get; set; }
        public Nullable<decimal> EuroChildTicketCost { get; set; }
        public Nullable<decimal> EuroFamilyTicketCost { get; set; }
        public Nullable<decimal> EuroConcessionTicketCost { get; set; }
        public Nullable<decimal> EuroGroupAdultTicketCost { get; set; }
        public Nullable<decimal> EuroGroupChildTicketCost { get; set; }
        public Nullable<decimal> PoundAdultTicketCost { get; set; }
        public Nullable<decimal> PoundChildTicketCost { get; set; }
        public Nullable<decimal> PoundFamilyTicketCost { get; set; }
        public Nullable<decimal> PoundConcessionTicketCost { get; set; }
        public Nullable<decimal> PoundGroupAdultTicketCost { get; set; }
        public Nullable<decimal> PoundGroupChildTicketCost { get; set; }
        public Nullable<bool> TimeSpecific { get; set; }
        public Nullable<int> StartTimeHour { get; set; }
        public Nullable<int> StartTimeMinute { get; set; }
        public Nullable<int> EndTimeHour { get; set; }
        public Nullable<int> EndTimeMinute { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public string Title { get; set; }
        public Nullable<bool> PercentageAppliesToAll { get; set; }
        public Nullable<decimal> PercentageAdult { get; set; }
        public Nullable<decimal> PercentageChild { get; set; }
        public Nullable<decimal> PercentageFamily { get; set; }
        public Nullable<decimal> PercentageConcession { get; set; }
        public Nullable<decimal> PercentageGroupAdult { get; set; }
        public Nullable<decimal> PercentageGroupChild { get; set; }
        public Nullable<decimal> AEDAdultTicketCost { get; set; }
        public Nullable<decimal> AEDChildTicketCost { get; set; }
        public Nullable<decimal> AEDFamilyTicketCost { get; set; }
        public Nullable<decimal> AEDConcessionTicketCost { get; set; }
        public Nullable<decimal> AEDGroupAdultTicketCost { get; set; }
        public Nullable<decimal> AEDGroupChildTicketCost { get; set; }
        public Nullable<decimal> HKDAdultTicketCost { get; set; }
        public Nullable<decimal> HKDChildTicketCost { get; set; }
        public Nullable<decimal> HKDFamilyTicketCost { get; set; }
        public Nullable<decimal> HKDConcessionTicketCost { get; set; }
        public Nullable<decimal> HKDGroupAdultTicketCost { get; set; }
        public Nullable<decimal> HKDGroupChildTicketCost { get; set; }
        public Nullable<decimal> DollarInfantTicketCost { get; set; }
        public Nullable<decimal> EuroInfantTicketCost { get; set; }
        public Nullable<decimal> PoundInfantTicketCost { get; set; }
        public Nullable<decimal> PercentageInfant { get; set; }
        public Nullable<decimal> AEDInfantTicketCost { get; set; }
        public Nullable<decimal> HKDInfantTicketCost { get; set; }
    
        public virtual tb_Ticket tb_Ticket { get; set; }
    }
}
