//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ThingsToDoItem
    {
        public System.Guid Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> UtcDateCreated { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Microsite_Id { get; set; }
        public Nullable<System.Guid> ImageMetaData_Id { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string ReadMoreText { get; set; }
    }
}
