//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Ticket()
        {
            this.tb_AgentCommission = new HashSet<tb_AgentCommission>();
            this.tb_PlaceOfInterest = new HashSet<tb_PlaceOfInterest>();
            this.tb_Route = new HashSet<tb_Route>();
            this.tb_Ticket_ExclusionWeekday = new HashSet<tb_Ticket_ExclusionWeekday>();
            this.tb_TicketCost = new HashSet<tb_TicketCost>();
            this.tb_TicketCostVariation = new HashSet<tb_TicketCostVariation>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string TicketType { get; set; }
        public Nullable<System.Guid> ImageMetaData_Id { get; set; }
        public string MicroSite_Id { get; set; }
        public Nullable<System.Guid> SmallImageMetaData_Id { get; set; }
        public string Name { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> TicketImageMetaData_Id { get; set; }
        public bool TicketImageEnabled { get; set; }
        public string TicketTextTopLine { get; set; }
        public string TicketTextMiddleLine { get; set; }
        public string TicketTextBottomLine { get; set; }
        public Nullable<int> AttractionDisplayOrder { get; set; }
        public bool AdultTicketEnabled { get; set; }
        public bool ChildTicketEnabled { get; set; }
        public bool FamilyTicketEnabled { get; set; }
        public bool ConcessionTicketEnabled { get; set; }
        public bool GroupAdultTicketEnabled { get; set; }
        public bool GroupChildTicketEnabled { get; set; }
        public Nullable<bool> IsPackage { get; set; }
        public string Code { get; set; }
        public bool EnabledForAgents { get; set; }
        public bool HasMobile { get; set; }
        public string TicketTextLine2 { get; set; }
        public string TicketTextLine3 { get; set; }
        public bool AgentsOnly { get; set; }
        public bool IsRemittanceTicket { get; set; }
        public Nullable<System.Guid> CarouselImageMetaData_Id { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsTradeTicket { get; set; }
        public bool LimitFutureDatePurchase { get; set; }
        public int FutureDatePurchaseDayAmount { get; set; }
        public bool HasMobileAgent { get; set; }
        public Nullable<System.Guid> AttractionApi { get; set; }
        public bool InfantTicketEnabled { get; set; }
        public bool GroupInfantTicketEnabled { get; set; }
        public string EcrProductCode { get; set; }
        public string EcrProductDuration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_AgentCommission> tb_AgentCommission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PlaceOfInterest> tb_PlaceOfInterest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Route> tb_Route { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Ticket_ExclusionWeekday> tb_Ticket_ExclusionWeekday { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_TicketCost> tb_TicketCost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_TicketCostVariation> tb_TicketCostVariation { get; set; }
    }
}
