//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Transaction_Address
    {
        public System.Guid Id { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string Order_Id { get; set; }
        public string PayflowUtiliy_OrderId { get; set; }
        public string BillTo_FirstName { get; set; }
        public string BillTo_LastName { get; set; }
        public string BillTo_Street { get; set; }
        public string BillTo_Address1 { get; set; }
        public string BillTo_Address2 { get; set; }
        public string BillTo_City { get; set; }
        public string BillTo_Zip { get; set; }
        public string BillTo_PostCode { get; set; }
        public string BillTo_State { get; set; }
        public string BillTo_Country { get; set; }
        public string ShipTo_FirstName { get; set; }
        public string ShipTo_LastName { get; set; }
        public string ShipTo_Street { get; set; }
        public string ShipTo_Address1 { get; set; }
        public string ShipTo_Address2 { get; set; }
        public string ShipTo_City { get; set; }
        public string ShipTo_Zip { get; set; }
        public string ShipTo_State { get; set; }
        public string ShipTo_PostCode { get; set; }
        public string ShipTo_Country { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Title { get; set; }
        public string Session_Id { get; set; }
        public string Email { get; set; }
    }
}
