//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Ticket_Language
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Ticket_Id { get; set; }
        public string Language_Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool IsLiveVersion { get; set; }
        public string SalesText { get; set; }
        public string CarouselDescription { get; set; }
    }
}
