//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBus.DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_User()
        {
            this.tb_AgentCommission = new HashSet<tb_AgentCommission>();
            this.tb_Company = new HashSet<tb_Company>();
        }
    
        public System.Guid Id { get; set; }
        public string Type { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PasswordHash { get; set; }
        public int PasswordVersion { get; set; }
        public string ReminderChallenge { get; set; }
        public string ReminderAnswer { get; set; }
        public string Title { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
        public string StateProvince { get; set; }
        public string Country_Id { get; set; }
        public Nullable<bool> ReceiveNewsletter { get; set; }
        public string Language_Id { get; set; }
        public Nullable<System.Guid> Currency_Id { get; set; }
        public System.DateTime DateRegistered { get; set; }
        public string JobTitle { get; set; }
        public Nullable<System.Guid> Basket_Id { get; set; }
        public Nullable<System.Guid> Company_Id { get; set; }
        public bool Authorised { get; set; }
        public string AuthorisedBy_Id { get; set; }
        public bool IsAgent { get; set; }
        public string AgentProfile_Id { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string WebsiteURL { get; set; }
        public string CompanyName { get; set; }
        public string AgentNote { get; set; }
        public bool CanViewCompOrders { get; set; }
        public string MicroSite_Id { get; set; }
        public string CityPrefer { get; set; }
        public string FriendlyEmail { get; set; }
        public bool W9OnFile { get; set; }
        public bool MobileTicketAgent { get; set; }
        public bool IsECR { get; set; }
        public bool AllowCashSales { get; set; }
        public bool AllowCreditCardSales { get; set; }
        public bool IsAgentTandCAccepted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_AgentCommission> tb_AgentCommission { get; set; }
        public virtual tb_AgentProfile tb_AgentProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Company> tb_Company { get; set; }
    }
}
